
FROM odoo:17.0


RUN apt-get update && apt-get install -y \
    vim \
    git \
    wkhtmltopdf \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /mnt/extra-addons


COPY ./Enterprise /mnt/extra-addons/Enterprise
COPY ./Custom/Addons/l10n-dominicana /mnt/extra-addons/l10n-dominicana
COPY ./Custom/Addons/pos_order_barber /mnt/extra-addons/pos_order_barber


COPY ./odoo.conf /etc/odoo/odoo.conf
COPY ./entrypoint.sh /entrypoint.sh


RUN chmod +x /entrypoint.sh


ENV WKHTMLTOPDF_BIN=/usr/bin/wkhtmltopdf


ENTRYPOINT ["/entrypoint.sh"]

CMD ["odoo"]
