version: '3.8'

services:
  web:
    container_name: odoo-web
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - '8069:8069'
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./Custom/addons:/mnt/extra-addons
      - ./Enterprise:/mnt/Enterprise
      - ./Custom/Addons/l10n-dominicana:/mnt/extra-addons/l10n-dominicana  # Aquí añades la primera línea COPY
      - ./Custom/Addons/pos_order_barber:/mnt/extra-addons/pos_order_barber  # Aquí añades la segunda línea COPY
    networks:
      - default
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=postgres  # Nombre de la base de datos PostgreSQL
      - PGDATA=/var/lib/postgresql/data  # Ruta de datos de PostgreSQL
      - POSTGRES_HOST_AUTH_METHOD=trust  # Método de autenticación PostgreSQL
      
  db:
    container_name: odoo-db
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres-data:
  odoo-data:

networks:
  default:
